# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Year in a backpack
email: yearinabackpack@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of year round travel adventure around South America and Asia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yearinabackpack.com" # the base hostname & protocol for your site
twitter_username: yearinabackpack
github_username:  yearinabackpack

# Build settings
markdown: kramdown
theme: minima

include: ["_pages"]

defaults:
  -
    scope:
      path: ""
      type: "" # a collection in your site, in plural form
    values:
      layout: "default"